---
title: "chuva"
author: "Matheus"
output: html_document
---

```{r, echo=FALSE}
#Definindo padrões dos chuncks do Trabalho
knitr::opts_chunk$set(fig.width = 6, fig.height = 3.5, fig.path = 'Figs/', fig.align='center', echo=FALSE, warning = FALSE, message = FALSE)
```
##Pacotes

```{r}
library(tidyverse)
library(magrittr)
library(ggmap)
library(dplyr)
library(readxl)
library(tidyr)
library(lubridate)
library(gridExtra)
###
library(sp)
library(gstat)
```


```{r}
chuva <- read.csv("dados/pluieNA.novdec.csv",header = T)
estacao <- read.csv("dados/pluieStations.Practicum.csv",header = T,stringsAsFactors = F)
coord <- read_excel("dados/coord.xlsx")


names(chuva) <- c("n",estacao$nom) 
```

##Mapa


```{r}
France <- qmap("languedoc-roussillon", zoom = 8, 
               color, maptype = "toner")

France +
geom_point(aes(x = lon, y = lat), 
           col = "red", 
           size = 2, 
           data = coord[c(36,37),]) +
  geom_point(aes(x = lon, y = lat), 
             col = "blue", 
             size = 2,
data = coord[c(1,3),]) +
  geom_point(aes(x = lon, y = lat), 
             col = "green", 
             size = 2, 
             data = coord[-c(1,3,36,37),]) 
```


##Series comparando regiao azul com vermelha

```{r}
chuva_amostra <- chuva[,c(2,4,37,38)] %>% 
  mutate(ano = rep(1975:1992,each = 6), 
         mes = rep(11:12,each = 3,times = 18),
         dia = rep(c(10,20,30),times = 36),
         data = ymd(paste0(ano,mes,dia))) %>%
  select(-ano,-mes,-dia) %>% 
  gather(regiao,obs,-data) %>% 
  mutate(rg = ifelse(regiao %in%
                       c("Carcassonne","Limoux"),"A","V"))

p1 <- 
chuva_amostra %>%
  filter(rg == "A") %>% 
  ggplot(aes(data,obs)) +
  geom_line(col = "blue") +
  theme(x = NULL)+
  facet_grid(.~regiao)

p2 <- 
chuva_amostra %>%
  filter(rg == "V") %>% 
  ggplot(aes(data,obs)) +
  geom_line(col = "red") +
  theme(x = NULL)+
  facet_grid(.~regiao)

grid.arrange(p1,p2)
```


##Krigging primeira parte

inicialmente estamos desconsiderando  o comportamento temporal dos dados, no caso estaremos considerando como variavel resposta a média do total de chuva em cada umas das cidades

```{r}
chuva_media <- apply(chuva[,-1],2,mean,na.rm = T) %>%
 { data.frame(chuva = .) } %>% bind_cols(coord) %>%
  mutate(nome = estacao$nom)


chuva_media %>% 
  ggplot(aes(lon, lat)) +
  geom_point(aes(size = chuva), 
             color = "blue",
             alpha = 0.5) + 
  ggtitle("Média chuva por estacao") + 
  theme_bw()

```

##Variograma

```{r}
coordinates(chuva_media) <- ~ lon + lat
variograma <- variogram(chuva~1, chuva_media) 
fit <- fit.variogram(variograma, model = vgm("Exc"))
plot(variograma,fit,xlab="Distância (h)", ylab="Semivariograma")
```



```{r}
max_lat <- max(coord$lat)
max_lon <- max(coord$lon) 
min_lat <- min(coord$lat)
min_lon <- min(coord$lon)
chuva_grid <- expand.grid(lat =
                           seq(min_lat,max_lat,length.out = 200),
                         lon = 
                           seq(min_lon,max_lon,length.out = 200))

chuva_grid_filter <- chuva_grid %>%
  filter(lon < (min_lon + (max_lon - min_lon)*0.45) |
         lat > (max_lat - (max_lat - min_lat)*.55)) %>% 
  sample_n(200)
###previsao


coordinates(chuva_grid) <- ~ lon + lat
my_krig <- 
  krige(chuva~1, chuva_media, chuva_grid, model = fit)
df_krig <- my_krig %>% 
  as.data.frame() %>% 
  mutate()



```

##krigagem

```{r}
coord %<>% 
  mutate(estacao = estacao$nom)
df_krig %>% 
ggplot(aes(x = lon, y = lat)) + 
  geom_tile(aes(fill=var1.pred)) +
  scale_fill_gradient(low = "yellow", high="red") +
  geom_text(aes(x = lon, y = lat, label = estacao ), 
            data = coord,size = 2.5) +
  coord_cartesian(xlim = c(1.9,5.2)) +
  labs(fill = "Volume Chuva") +
  theme_bw()

df_krig %>% 
ggplot(aes(x = lon, y = lat)) + 
  geom_tile(aes(fill=var1.var)) +
  scale_fill_gradient(low = "yellow", high="red") +
  labs(fill = "Variância") +
  theme_bw() 



```

